// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC33Lr1pdGaSkYSJ3lloKpIlhtmzrMO-iA',
    appId: '1:607840749804:web:4963b08a4fe7f4c9157dc9',
    messagingSenderId: '607840749804',
    projectId: 'eventos-app-f3141',
    authDomain: 'eventos-app-f3141.firebaseapp.com',
    storageBucket: 'eventos-app-f3141.firebasestorage.app',
    measurementId: 'G-2N7314XR2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMQ9sInCIjCJGj-fZdEPBkNmSLpiqhvvM',
    appId: '1:607840749804:android:f8b7243e4c243966157dc9',
    messagingSenderId: '607840749804',
    projectId: 'eventos-app-f3141',
    storageBucket: 'eventos-app-f3141.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCa49EPapDafw6ZKkBrKNUJBW1UgyJH4XA',
    appId: '1:607840749804:ios:84913a0ae6d645e8157dc9',
    messagingSenderId: '607840749804',
    projectId: 'eventos-app-f3141',
    storageBucket: 'eventos-app-f3141.firebasestorage.app',
    iosBundleId: 'com.2m.eventosApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCa49EPapDafw6ZKkBrKNUJBW1UgyJH4XA',
    appId: '1:607840749804:ios:84913a0ae6d645e8157dc9',
    messagingSenderId: '607840749804',
    projectId: 'eventos-app-f3141',
    storageBucket: 'eventos-app-f3141.firebasestorage.app',
    iosBundleId: 'com.2m.eventosApp',
  );
}
